// src/frameworks/react/TicketpingChat.js
import { useEffect, useRef } from 'react';

/**
 * Ticketping Chat Widget component for React
 * Uses the @ticketping/chat-widget npm package
 */
const TicketpingChat = ({
  appId,
  teamSlug,
  teamLogoIcon,
  apiBase = 'https://api.ticketping.com',
  wsBase = 'wss://api.ticketping.com',
  userJWT,
  debug = false,
  showPulseAnimation = true,
  analytics = true,
  theme,
  onReady = () => {},
  onError = (e) => {
    console.error('Ticketping Chat Widget error:', e);
  },
  onOpen = () => {},
  onClose = () => {},
  onMessageSent = () => {},
  onMessageReceived = () => {},
  onConversationStarted = () => {},
}) => {
  const widgetRef = useRef(null);
  const widgetReadyRef = useRef(false);

  useEffect(() => {
    // Only run on client side
    if (typeof window === 'undefined') {
      return;
    }

    const loadWidget = async () => {
      try {
        // Dynamic import of the widget package
        await import('@ticketping/chat-widget');

        // Import CSS
        await import('@ticketping/chat-widget/style');

        // Configuration object
        const config = {
          appId,
          teamSlug,
          teamLogoIcon,
          apiBase,
          wsBase,
          userJWT,
          debug,
          showPulseAnimation,
          analytics,
          theme,
          onReady: () => {
            widgetReadyRef.current = true;
            onReady?.();
          },
          onOpen,
          onClose,
          onMessageSent,
          onMessageReceived,
          onConversationStarted,
          onError,
        };

        // Initialize the widget
        widgetRef.current = window.TicketpingChat.init(config);
      } catch (error) {
        console.error('Failed to load Ticketping Chat Widget:', error);
        onError?.(error);
      }
    };

    loadWidget();

    // Cleanup on unmount
    return () => {
      if (widgetRef.current) {
        widgetRef.current.destroy();
        widgetRef.current = null;
        widgetReadyRef.current = false;
      }
    };
  }, []); // Only run once on mount

  return null; // Widget renders itself into DOM
};

export default TicketpingChat;

// examples/svelte/TicketpingChat.svelte
<script>
  import { onMount, onDestroy } from 'svelte';

  // Props - Configuration for the widget
  let {
    appId = '',
    teamSlug = '',
    teamLogoIcon = '',
    apiBase = 'https://api.ticketping.com',
    wsBase = 'wss://api.ticketping.com',
    userJWT = null,
    debug = false,
    showPulseAnimation = true,
    analytics = true,
    theme = null,
    open = false,
    user = null,
    // Event handlers
    onready = () => {},
    onopen = () => {},
    onclose = () => {},
    onmessageSent = () => {},
    onmessageReceived = () => {},
    onconversationStarted = () => {},
    onerror = () => {}
  } = $props();

  let widget = $state(null);
  let widgetReady = $state(false);

  // Configuration object - derived from props
  const config = $derived({
    appId,
    teamSlug,
    teamLogoIcon,
    apiBase,
    wsBase,
    userJWT,
    debug,
    showPulseAnimation,
    analytics,
    theme,
    // Event callbacks that call the provided handlers
    onReady: () => {
      widgetReady = true;
      onready();
    },
    onOpen: () => {
      onopen();
    },
    onClose: () => {
      onclose();
    },
    onMessageSent: (message) => {
      onmessageSent(message);
    },
    onMessageReceived: (message) => {
      onmessageReceived(message);
    },
    onConversationStarted: (id) => {
      onconversationStarted(id);
    },
    onError: (error) => {
      onerror(error);
    }
  });

  // Effect to handle open/close when prop changes
  $effect(() => {
    if (widget && widgetReady) {
      if (open) {
        widget.open();
      } else {
        widget.close();
      }
    }
  });

  // Effect to handle user identification
  $effect(() => {
    if (widget && widgetReady && user) {
      widget.identify(user);
    }
  });

    onMount(async () => {
    // Dynamic import to avoid SSR issues
    if (typeof window !== 'undefined') {
      try {
        // Import the widget
        const TicketpingChat = await import('@ticketping/chat-widget');

        // Import CSS
        await import('@ticketping/chat-widget/style');

        // Initialize the widget
        widget = window.TicketpingChat.init(config);

        // If user is provided on mount, identify them
        if (user) {
          widget.identify(user);
        }

        // Open widget if prop is set
        if (open) {
          widget.open();
        }

      } catch (error) {
        console.error('Failed to load Ticketping Chat Widget:', error);
        onerror(error);
      }
    }
  });

  onDestroy(() => {
    // Clean up widget when component is destroyed
    if (widget) {
      widget.destroy();
      widget = null;
      widgetReady = false;
    }
  });

  // Public methods that can be called from parent components
  export function openWidget() {
    if (widget && widgetReady) {
      widget.open();
    }
  }

  export function closeWidget() {
    if (widget && widgetReady) {
      widget.close();
    }
  }

  export function toggleWidget() {
    if (widget && widgetReady) {
      widget.toggle();
    }
  }

  export function startConversation() {
    if (widget && widgetReady) {
      return widget.startConversation();
    }
  }

  export function identifyUser(userData) {
    if (widget && widgetReady) {
      widget.identify(userData);
    }
  }

  export function isReady() {
    return widgetReady;
  }
</script>

<!--
  The widget renders itself into the DOM, so this component doesn't need any markup.
  We could add a loading state or error state here if needed.
-->

{#if !widgetReady && debug}
  <div class="ticketping-loading" style="position: fixed; bottom: 20px; right: 20px; z-index: 999;">
    Loading chat widget...
  </div>
{/if}

<style>
  .ticketping-loading {
    background: rgba(0, 0, 0, 0.8);
    color: white;
    padding: 8px 12px;
    border-radius: 4px;
    font-size: 12px;
  }
</style>
